version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: timedeposit-db
    environment:
      POSTGRES_DB: timedeposit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - timedeposit-data:/var/lib/postgresql/data

volumes:
  timedeposit-data: